# Generated by Django 5.1.6 on 2025-02-06 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(help_text='detailed description of the exercise.')),
                ('instructions', models.TextField(help_text='Instruction for proper excution.')),
                ('target_muscles', models.CharField(help_text='target muscles', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='tracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(help_text='recorded wieght of the user')),
                ('date', models.DateField(auto_now_add=True)),
                ('note', models.TextField(blank=True, help_text='optional note for this tracking entry.', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Name of the workout plan', max_length=100)),
                ('session_duration', models.DurationField(help_text='planned for each workout session (HH:MM:SS)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(help_text='the user who created workoout plan', on_delete=django.db.models.deletion.CASCADE, related_name='Workout_plan', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutPlanExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repetitions', models.PositiveIntegerField(blank=True, help_text='number of sets, if applicable', null=True)),
                ('distance', models.FloatField(blank=True, help_text='distance if applicable for running', null=True)),
                ('duration', models.DurationField(blank=True, help_text='duration for exercise if applicabe', null=True)),
                ('sets', models.PositiveIntegerField(blank=True, help_text='number of sets applicable', null=True)),
                ('exsercies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.exercise')),
                ('wokrout_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='workouts.workoutplan')),
            ],
        ),
    ]
