# Generated by Django 5.1.6 on 2025-02-06 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='distance',
            field=models.FloatField(blank=True, help_text='distance if applicable for running', null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='duration',
            field=models.DurationField(blank=True, help_text='duration for exercise if applicabe', null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='sets',
            field=models.PositiveIntegerField(blank=True, help_text='number of sets applicable', null=True),
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='user_workouts',
            field=models.ManyToManyField(to='workouts.exercise'),
        ),
        migrations.DeleteModel(
            name='WorkoutPlanExercise',
        ),
    ]
